---
- hosts: localhost
  gather_facts: no
  vars_files:
    - ./vars/external_vars.yml

  tasks:    
    - name: Terraform Deploy/Destroy Infrastructure
      terraform:
        project_path: ../terraform/kafka-zk/
        force_init: true
        state: present
        variables:
          region: "{{region}}"
          vpc_id: "{{vpc_id}}"
          subnet_id_0: "{{subnet_id_0}}"
          subnet_id_1: "{{subnet_id_1}}"
          subnet_id_2: "{{subnet_id_2}}"
          s3_bucket_name: "{{s3_bucket_name}}"
          instance_count: "{{instance_count}}"
          environment: "{{environment_name}}"
          my_public_ip: "{{my_public_ip}}"
          ami_id: "{{ami_id}}"
          instance_type: "{{instance_type}}"
          key_name: "{{key_name}}"
          root_volume_size: "{{root_volume_size}}"
      register: output_result

    - debug:
        msg: "{{output_result.stdout}}"
    
    - set_fact:
        private_ips: "{{output_result.outputs.private_ips.value}}"
        public_ips: "{{output_result.outputs.public_ips.value}}"
        real_bucket_name: "{{output_result.outputs.exhibitor_s3_bucket.value}}"
  
    - set_fact:
        zookeeper_connect: "{{private_ips | map('regex_replace', '$', ':2181') | list}}"

    - name: Additional Info in the inventory
      blockinfile:
          path: dyn_inven
          marker: "# {mark} ANSIBLE MANAGED BLOCK FOR KAFKA-NODES VARIABLES"
          state: present
          block: |
            [kafka-nodes:vars]
            ansible_ssh_user=ubuntu
            ansible_ssh_private_key_file=./kafka_zk_clusterkey.pem
            ansible_ssh_common_args='-o StrictHostKeyChecking=no'
            real_bucket_name={{real_bucket_name}} 
            zookeeper_connect=
            
    - name: Adding Zookeeper_Connect Info in the Inventory
      lineinfile:
          dest: dyn_inven
          regexp: '^zookeeper_connect='
          line: "zookeeper_connect={{zookeeper_connect | join(',')}}"

    - name: Refresh inventory for new hosts
      meta: refresh_inventory
    
 
- hosts: [kafka-nodes]
  vars_files:
    - ./vars/external_vars.yml

  tasks:
    - include_tasks:  ../../tasks/start.yaml
