---

- debug:
    msg: "{{output_result.stdout}}"
    
- set_fact:
    private_ips: "{{output_result.outputs.private_ips.value}}"
    real_bucket_name: "{{output_result.outputs.exhibitor_s3_bucket.value}}"

- set_fact:
    zookeeper_connect: "{{private_ips | map('regex_replace', '$', ':2181') | list}}"
- name: Additional Info in the inventory
  blockinfile:
      path: dyn_inven
      marker: "# {mark} ANSIBLE MANAGED BLOCK FOR KAFKA-NODES VARIABLES"
      state: present
      block: |
        [kafka-nodes:vars]
        ansible_ssh_user=ubuntu
        ansible_ssh_private_key_file=./{{key_name}}.pem
        ansible_ssh_common_args='-o StrictHostKeyChecking=no'
        real_bucket_name={{real_bucket_name}} 
        zookeeper_connect=
        
- name: Adding Zookeeper_Connect Info in the Inventory
  lineinfile:
      dest: dyn_inven
      regexp: '^zookeeper_connect='
      line: "zookeeper_connect={{zookeeper_connect | join(',')}}"
- name: Refresh inventory for new hosts
  meta: refresh_inventory
