---
- hosts: kafka-host
  become: yes
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
  
  tasks:
    - name: Add Docker GPG key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker APT repository
      apt_repository:
       repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

    - name: Install list of packages
      apt:
        name: "{{ item }}"
        state: installed
        update_cache: yes
      with_items:
       - apt-transport-https
       - ca-certificates
       - curl
       - software-properties-common
       - docker-ce
       - python3-pip
     
    - name: Install Docker SDK for Python
      pip:
       name: 'docker'
    
    - name: Add User ubuntu to Docker Group
      user:
        name: 'ubuntu'
        groups: 'docker'
        append: 'yes'

       
    - name: Clone Git Repo for Building Docker image for Kafka
      git:
        repo: 'https://github.com/ArsiKhan/kafka-aws.git'
        clone: yes
        update: yes
        dest: /home/ubuntu/kafka-aws
        
    - name: Build Kafka Container Image
      docker_image:
        name: kafka
        tag: 2.11_2.4.0
        build:
          path: /home/ubuntu/kafka-aws/docker
          args:
            kafka_version: 2.4.0
            scala_version: 2.11
     
    - name: Pull Zookeeper-Exhibitor Container Image
      docker_image:
        name: 'mbabineau/zookeeper-exhibitor:latest'
        source: pull
     