---
- hosts: localhost

  tasks:
    - name: Terraform Provision VPC
      terraform:
        project_path: ../terraform/kafka-zk/
        force_init: true
        targets: module.vpc
        state: present
    
    - name: Terraform Deploy Remaining Infrastructure
      terraform:
        project_path: ../terraform/kafka-zk/
        state: present
      register: output_result
    
    - debug:
        var: output_result.outputs.kafka_cluster_ips.value[0]

