---
- hosts: localhost
  gather_facts: no
  vars_files:
    - ./vars/external_vars.yml

  tasks:
    
    - name: Terraform Deploy/Destroy Infrastructure
      terraform:
        project_path: ../terraform/kafka-zk/
        force_init: true
        state: present
        variables:
          region: "{{region}}"
          vpc_cidr: "{{vpc_cidr}}"
          subnet_0: "{{subnet_0}}"
          subnet_1: "{{subnet_1}}"
          subnet_2: "{{subnet_2}}"
          s3_bucket_name: "{{s3_bucket_name}}"
          instance_count: "{{instance_count}}"
          environment: "{{environment_name}}"
          my_public_ip: "{{my_public_ip}}"
          ami_id: "{{ami_id}}"
          instance_type: "{{instance_type}}"
          key_name: "{{key_name}}"
          root_volume_size: "{{root_volume_size}}"
      register: output_result

    - include_tasks:  ../../tasks/deploy.yaml


- hosts: [kafka-nodes]
  gather_facts: no
  vars_files:
    - ./vars/external_vars.yml

  tasks:
    - include_tasks:  ../../tasks/start.yaml
